Fix putscom for odyssey chips
Added the changes to support putscom for odyssey chips. These changes
will support putscom from command line.

Test Results:
root@p10bmc:/tmp# putscom odyssey c0002040 -p2 deadbeefdeadbeef
odyssey k0:n0:s0:p02
/usr/bin/edbg putscom odyssey c0002040 -p2 deadbeefdeadbeef

root@p10bmc:/tmp# getscom odyssey c0002040 -all
odyssey k0:n0:s0:p02       0xDEADBEEFDEADBEEF
odyssey k0:n0:s0:p03       0x004011000A000640
odyssey k0:n0:s0:p34       0x004011000A000640
odyssey k0:n0:s0:p35       0x004011000A000640
/usr/bin/edbg getscom odyssey c0002040 -all

root@p10bmc:/tmp# putscom odyssey c0002040 -p2 004011000A000640
odyssey k0:n0:s0:p02
/usr/bin/edbg putscom odyssey c0002040 -p2 004011000A000640

root@p10bmc:/tmp# getscom odyssey c0002040 -all
odyssey k0:n0:s0:p02       0x004011000A000640
odyssey k0:n0:s0:p03       0x004011000A000640
odyssey k0:n0:s0:p34       0x004011000A000640
odyssey k0:n0:s0:p35       0x004011000A000640
/usr/bin/edbg getscom odyssey c0002040 -all

root@p10bmc:/tmp# getscom explorer c0002040 -all
ERROR: (ECMD): getscom - Unable to find a valid chip to execute command on
ERROR: (ECMD): ecmd - 'getscom' returned with error code 0x100100F (ERROR OPENING DECODE FILE)
/usr/bin/edbg getscom explorer c0002040 -all

Signed-off-by: Deepa Karthikeyan <deepakala.karthikeyan@ibm.com>